export const ADICIONAR_NOME = 'ADICIONAR_NOME';
export const REMOVER_NOME = 'REMOVER_NOME';
export const ADICIONAR_ENDERECO = 'ADICIONAR_ENDERECO';
export const REMOVER_ENDERECO = 'REMOVER_ENDERECO';
export const LOGIN_LOGAR = 'LOGIN_LOGAR';
export const PEDIDOS_CONSULTAR = 'PEDIDOS_CONSULTAR';
export const LOADING_EXIBIR = 'LOADING_EXIBIR';
export const LOADING_OCULTAR = 'LOADING_OCULTAR';
